### ISSUE TITLE
Edgar import issue

### ISSUE THREAD

**Issue by oneryalcin** [virattt/financial-datasets#1]
Hi @virattt , many thanks for the financial-datasets library, I was just taking it for a test ride but noticed it does give an error when I try it:

```python
from financial_datasets.generator import DatasetGenerator
```

Error
```python
ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-17-0e0d452e68f1>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from financial_datasets.generator import DatasetGenerator
      2 
      3 # generator = DatasetGenerator(model="gpt-3.5-turbo", api_key="s..")
      4 
      5 # # Generate dataset from texts

1 frames

[/usr/local/lib/python3.10/dist-packages/financial_datasets/filings.py](https://localhost:8080/#) in <module>
      1 from datetime import datetime
      2 
----> 3 from edgar._companies import EntityFilings, EntityFiling
      4 
      5 

ModuleNotFoundError: No module named 'edgar._companies'
```

Looks like the issue comes from the dependency on edgartools, as highlighted in the error message edgar._companies doesn't have `EntityFilings` or `EntityFiling` class. These classes are available in `edgar.entities` module

Important Note: This only happens with `edgartools` latest version 2.18

**Comment by virattt** [comment]
Thanks for calling out @oneryalcin.  Not sure what happened with edgartools (cc @dgunning), but I have removed the imports from financial-datsets.

**Comment by virattt** [comment]
I've also updated financial-datasets so it only depends on the last working version of edgartools (2.16.1) so this does not happen again.

**Comment by oneryalcin** [comment]
Thanks @virattt , looks all good now :)
